export const URL = 'https://api.punkapi.com/v2/beers';

export const FETCH_DATA_BEGINS = 'FETCH_DATA_BEGINS';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const NAVIGATE_TO_DASHBOARD = 'NAVIGATE_TO_DASHBOARD';
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES';
export const LIST_FAVOURITES = 'LIST_FAVOURITES';